[package]
name = "game-api"
version = "0.1.0"
authors = ["Martin L. Jensen <martinloesethjensen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "0.3.11"
dotenv = "0.15.0"
r2d2 = "0.8.9"
r2d2-mongodb = "0.2.2"
rocket = "0.4.7"
rocket_contrib = "0.4.7"
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
serde_json = "1"