[global.databases.games_db]
url = "postgres://postgres:password@localhost/games_db"

[development]
address = "localhost"
port = 8000
workers = 8
log = "normal"
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 80
workers = 8
log = "normal"
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 80
workers = 8
log = "critical"
limits = { forms = 32768 }
